apiVersion: v1
kind: Service
metadata:
  name: secure-demo
  labels:
    app: secure-demo
spec:
  selector:
    app: secure-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer